# Generated by Django 4.2.16 on 2024-12-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='pic.png', upload_to='profile_pictures'),
        ),
    ]
