# Generated by Django 4.2.16 on 2024-12-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csadmin', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='pic.png', null=True, upload_to='profile_pictures'),
        ),
    ]
