# Generated by Django 4.2.16 on 2024-12-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csadmin', '0006_post_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
    ]
